apiVersion: apps/v1
kind: Deployment
metadata:
  name: jimdel-go-portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jimdel-go-portfolio
  template:
    metadata:
      labels:
        app: jimdel-go-portfolio
    spec:
      containers:
        - name: jimdel-go-portfolio
          image: delayj/jimdel-go-portfolio:latest
          ports:
            - containerPort: 3000
