// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navigation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data=\"{open: false}\"><nav class=\"w-full bg-slate-900 text-white p-4 flex justify-between z-50\"><a href=\"/\"><i class=\"fa-solid fa-hand-peace text-white text-3xl cursor-pointer\"></i></a> <i @click=\"open = !open\" x-show=\"!open\" class=\"fa-solid fa-bars fade-out text-white text-3xl cursor-pointer\"></i><div id=\"nav-menu\" x-show=\"open\" x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"transform translate-x-full\" x-transition:enter-end=\"transform translate-x-0\" x-transition:leave=\"transition ease-in duration-300\" x-transition:leave-start=\"transform translate-x-0\" x-transition:leave-end=\"transform translate-x-full\" class=\"h-screen w-full absolute top-0 left-0 bg-slate-900 z-50\"><div class=\"w-full flex justify-between p-4\"><a href=\"/\" class=\"cursor-pointer mx-auto\"><i class=\"fa-solid fa-hand-peace text-white text-6xl\"></i></a> <i x-show=\"open\" @click=\"open = !open\" class=\"fa-solid fa-close text-white text-4xl cursor-pointer absolute top-4 right-4\"></i></div><nav class=\"flex flex-col items-center gap-4 mt-24\"><a @click=\"open = !open\" href=\"/about\" class=\"text-3xl my-2\">About</a> <a @click=\"open = !open\" href=\"/blog\" class=\"text-3xl my-2\">Blog</a><a @click=\"open = !open\" href=\"/contact\" class=\"text-3xl my-2\">Contact</a></nav></div></nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
