# Image configuration - Flux will override the tag
image:
  repository: delayj/jimdel
  tag: latest  # This will be overridden by Flux
  pullPolicy: IfNotPresent

# App configuration
replicaCount: 2

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080  # Adjust to app's port

# INFO: managed by HelmRelease 
# # Ingress configuration
# ingress:
#   enabled: true
#   className: traefik
#   host: jimdel.dev # Update with domain
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.tls: "true"
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#   tls:
#     enabled: true
#     secretName: jimdel-tls

# Resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Any other app-specific values you have