# Image configuration - Flux will override the tag
image:
  repository: delayj/jimdel
  tag: latest  # This will be overridden by Flux
  pullPolicy: IfNotPresent

# App configuration
replicaCount: 2

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080  # Adjust to app's port

# # Ingress configuration
# INFO: managed by HelmRelease 

# Resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Any other app-specific values you have