# globals
applicationName: jimdel

# deployment.yaml 
deployment:
  replicaCount: 2
  containerPort: 3000

# image configuration - restructured for Flux compatibility
image:
  repository: delayj/jimdel
  tag: latest
  pullPolicy: Always

# service.yaml
service:
  targetPort: 8080

# ingress.yaml
ingress:
  host: jimdel.dev

# certmanager
certmanager:
  contactEmail: "jim@jim.com" #TODO: load from env